Remove `test_data` with in-memory image generation
MST-ACM/ACM_Website pull request #159
Opened 2018-01-22 04:00 UTC by kevinschoonover

Closes #148.

2018-01-22 06:19 UTC, zdw27f commented on ACM_General/events/tests.py
> -from datetime import datetime
The imports here should be alphabetically organized.

2018-01-22 06:21 UTC, zdw27f commented on ACM_General/rest_api/tests.py
>  import json
imports should be alphabetically organized.

2018-01-22 06:22 UTC, ZachWileman requested changes
Imports should be alphabetically organized.

2018-01-22 19:50 UTC, kevinschoonover commented
Should be fixed now @zdw27f

2018-01-24 05:29 UTC, ZachWileman approved these changes

2018-01-24 05:30 UTC, merged