Much better compatibility
MST-ACM/ACM_Website pull request #68
Opened 2017-08-17 00:54 UTC by ClayMav

Spent my whole day doing some testing in IE, Mozilla, Firefox and Chrome. Need more testing on these browsers:

- Edge 14+
- Safari 9.1+
- Opera 46+
- iOS Safari 9.3+
- Opera Mini
- Android Browser 4.1+
- Chrome for Android 59+
- Firefox for Android 54+
- IE Mobile 11+
- UC Browser for Android 11.4+
- Samsung Browser 4+

2017-08-17 02:46 UTC, kevinschoonover requested changes

2017-08-17 02:46 UTC, kevinschoonover commented on ACM_General/home/static/home/scss/404.scss
> +  /*margin: auto;*/
If you need it for something, put a comment as to why; Otherwise, please remove for slimmer code.

2017-08-17 02:46 UTC, kevinschoonover commented on ACM_General/home/static/home/scss/404.scss
> +  /*margin: auto;*/
Same here

2017-08-17 02:46 UTC, kevinschoonover commented on ACM_General/home/templates/home/base.html
> +      <label class="menu-toggle" for="menu"><span></span><span></span><span></span></label>
A lot of empty spans here? I'm assuming the is hamburger formatting or something of the like

2017-08-17 02:46 UTC, kevinschoonover commented on config.rb
> +css_dir = "/ACM_General/home/static/home/css"
These are all pointing to home. Any way to get them to point to all apps?

2017-08-17 02:49 UTC, kevinschoonover commented
Moreover, with regards to the sass and css, Its not really good git practice to have both the *.scss files and the *.css files because the scss compiles into css. I know you have not fully committed to sass quite yet, but just keep that in mind for if you decide to fully adopt sass that only.

2017-08-17 20:17 UTC, ClayMav commented on ACM_General/home/templates/home/base.html
> +      <label class="menu-toggle" for="menu"><span></span><span></span><span></span></label>
hamburger yes, switched from icon in previous versions to reduce load times

2017-08-17 20:18 UTC, ClayMav commented
What is it that you mean Kevin, should I .gitignore the css directory? I think I am fully sass as of right now.

2017-08-17 21:00 UTC, ClayMav commented on config.rb
> +css_dir = "/ACM_General/home/static/home/css"
I think each watch command can only do 1-1 directories with compass.
We will have to look into this later.

Can you port this over to an issue?

2017-08-17 22:57 UTC, kevinschoonover commented
Oh, I mean that you should completely remove all css files.

2017-08-18 02:01 UTC, kevinschoonover commented on config.rb
> +css_dir = "/ACM_General/home/static/home/css"
Done

2017-08-18 02:02 UTC, kevinschoonover approved these changes

2017-08-18 04:50 UTC, merged